### ISSUE TITLE
Fix Design Rules in Arduino Shield Template

### ISSUE THREAD

**Issue by llim1** [qfsae/pcb#22]
Re-import [2-layer 1-oz](https://github.com/ayberkozgur/jlcpcb-design-rules-stackups/blob/668069d5d316068e86e8497e96425a15b59bb8cc/design-rules/altium/2layer-1oz.RUL) JLCSMT design rules to [Arduino Uno shield template](https://github.com/qfsae/pcb/tree/master/reference/UNOR3Shield_Blank).

**Comment by ethanmpeterson** [comment]
Also fix the lack of an altium output job
